# Generated by Django 5.2.12 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='camera_source',
            field=models.CharField(default='0', help_text='Webcam index (0, 1) or full IP camera stream URL', max_length=255),
        ),
    ]
