# Generated by Django 5.2.12 on 2026-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_camera_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
