# Generated by Django 5.2.12 on 2026-10-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alert_unknown',
            field=models.BooleanField(default=True, help_text='Notify members and keep a snapshot when an unrecognised face is at the door'),
        ),
    ]
