# Generated by Django 5.0.2 on 2025-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='guest_qrs/')),
                ('encryption_key', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
