# Generated by Django 5.0.2 on 2025-04-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_facerecord_delete_guestqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecord',
            name='image',
            field=models.ImageField(upload_to='detected_faces/'),
        ),
    ]
