# Generated by Django 5.0.2 on 2025-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_facerecord_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('expiration_time', models.IntegerField()),
            ],
        ),
    ]
