# Generated by Django 5.0.2 on 2025-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='expiration_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
