# Generated by Django 5.0.2 on 2025-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_guest_expiration_time_alter_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='encryption_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='expiration_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
