# Generated by Django 5.0.2 on 2025-04-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_guest_encryption_key_alter_guest_expiration_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='site_users',
            name='face_embedding_file',
            field=models.FileField(blank=True, null=True, upload_to='face_embeddings/'),
        ),
        migrations.AddField(
            model_name='site_users',
            name='face_image',
            field=models.ImageField(default='', upload_to='user_faces/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_users',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.device'),
            preserve_default=False,
        ),
    ]
