# Generated by Django 5.0.2 on 2025-04-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_device_site_users_face_embedding_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_records', to='main_app.device'),
        ),
    ]
