# Generated by Django 5.0.2 on 2025-04-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_device_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
    ]
