# Generated by Django 5.0.2 on 2025-04-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_owner_name_device_name_remove_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='product_number',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
