# Generated by Django 5.0.2 on 2025-04-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_device_product_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='id',
        ),
    ]
