# Generated by Django 5.0.2 on 2025-04-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_device_id_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='main_app.site_users'),
            preserve_default=False,
        ),
    ]
